- hosts: jenkins-master
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - gnupg
          - curl
          - software-properties-common
        state: present

    - name: Download Jenkins GPG key to keyring
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository using signed-by keyring
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install OpenJDK 17 (default repo)
      apt:
        name: openjdk-17-jre
        state: present

    - name: Set Java 17 as default
      alternatives:
        name: java
        path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        priority: 1

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is started
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins to start on boot
      service:
        name: jenkins
        enabled: yes

